export default {
    "city-food": "Gather Food",
    "city-lumber": "Gather Lumber",
    "city-stone": "Gather Stone",
    "city-chrysotile": "Gather Chrysotile",
    "city-slaughter": "Slaughter the Weak",
    "city-horseshoe": "Horseshoe",
    "city-slave_market": "Slave Market",
    "city-s_alter": "Sacrificial Altar",
    "city-basic_housing": "Cabin",
    "city-cottage": "Cottage",
    "city-apartment": "Apartment",
    "city-lodge": "Lodge",
    "city-smokehouse": "Smokehouse",
    "city-soul_well": "Soul Well",
    "city-slave_pen": "Slave Pen",
    "city-transmitter": "Transmitter",
    "city-captive_housing": "Captive Housing",
    "city-farm": "Farm",
    "city-compost": "Compost Heap",
    "city-mill": "Windmill",
    "city-windmill": "Windmill (Evil)",
    "city-silo": "Grain Silo",
    "city-assembly": "Assembly",
    "city-garrison": "Barracks",
    "city-hospital": "Hospital",
    "city-boot_camp": "Boot Camp",
    "city-shed": "Shed",
    "city-storage_yard": "Freight Yard",
    "city-warehouse": "Container Port",
    "city-bank": "Bank",
    "city-pylon": "Pylon",
    "city-graveyard": "Graveyard",
    "city-conceal_ward": "Conceal Ward (Witch Hunting)",
    "city-lumber_yard": "Lumber Yard",
    "city-sawmill": "Sawmill",
    "city-rock_quarry": "Rock Quarry",
    "city-cement_plant": "Cement Plant",
    "city-foundry": "Foundry",
    "city-factory": "Factory",
    "city-nanite_factory": "Nanite Factory",
    "city-smelter": "Smelter",
    "city-metal_refinery": "Metal Refinery",
    "city-mine": "Mine",
    "city-coal_mine": "Coal Mine",
    "city-oil_well": "Oil Derrick",
    "city-oil_depot": "Fuel Depot",
    "city-trade": "Trade Post",
    "city-wharf": "Wharf",
    "city-tourist_center": "Tourist Center",
    "city-amphitheatre": "Amphitheatre",
    "city-casino": "Casino",
    "city-temple": "Temple",
    "city-shrine": "Shrine",
    "city-meditation": "Meditation Chamber",
    "city-banquet": "Banquet Hall",
    "city-university": "University",
    "city-library": "Library",
    "city-wardenclyffe": "Wardenclyffe",
    "city-biolab": "Bioscience Lab",
    "city-coal_power": "Coal Powerplant",
    "city-oil_power": "Oil Powerplant",
    "city-fission_power": "Fission Reactor",
    "city-mass_driver": "Mass Driver",

    "space-test_launch": "Space Test Launch",
    "space-satellite": "Space Satellite",
    "space-gps": "Space Gps",
    "space-propellant_depot": "Space Propellant Depot",
    "space-nav_beacon": "Space Navigation Beacon",

    "space-moon_mission": "Moon Mission",
    "space-moon_base": "Moon Base",
    "space-iridium_mine": "Moon Iridium Mine",
    "space-helium_mine": "Moon Helium-3 Mine",
    "space-observatory": "Moon Observatory",

    "space-red_mission": "Red Mission",
    "space-spaceport": "Red Spaceport",
    "space-red_tower": "Red Space Control",
    "space-captive_housing": "Red Captive Housing (Cataclysm)",
    "space-terraformer": "Red Terraformer (Orbit Decay)",
    "space-atmo_terraformer": "Red Terraformer (Orbit Decay, Complete)",
    "space-terraform": "Red Terraform (Orbit Decay)",
    "space-assembly": "Red Assembly (Cataclysm)",
    "space-living_quarters": "Red Living Quarters",
    "space-pylon": "Red Pylon (Cataclysm)",
    "space-vr_center": "Red VR Center",
    "space-garage": "Red Garage",
    "space-red_mine": "Red Mine",
    "space-fabrication": "Red Fabrication",
    "space-red_factory": "Red Factory",
    "space-nanite_factory": "Red Nanite Factory (Cataclysm)",
    "space-biodome": "Red Biodome",
    "space-red_university": "Red University (Orbit Decay)",
    "space-exotic_lab": "Red Exotic Materials Lab",
    "space-ziggurat": "Red Ziggurat",
    "space-space_barracks": "Red Marine Barracks",
    "space-horseshoe": "Red Horseshoe (Cataclysm)",

    "space-hell_mission": "Hell Mission",
    "space-geothermal": "Hell Geothermal Plant",
    "space-hell_smelter": "Hell Smelter",
    "space-spc_casino": "Hell Space Casino",
    "space-swarm_plant": "Hell Swarm Plant",

    "space-sun_mission": "Sun Mission",
    "space-swarm_control": "Sun Control Station",
    "space-swarm_satellite": "Sun Swarm Satellite",
    "space-jump_gate": "Sun Jump Gate",

    "space-gas_mission": "Gas Mission",
    "space-gas_mining": "Gas Helium-3 Collector",
    "space-gas_storage": "Gas Fuel Depot",
    "space-star_dock": "Gas Space Dock",
    "space-gas_moon_mission": "Gas Moon Mission",
    "space-outpost": "Gas Moon Mining Outpost",
    "space-drone": "Gas Moon Mining Drone",
    "space-oil_extractor": "Gas Moon Oil Extractor",

    "starDock-probes": "Space Dock Probe",
    "starDock-geck": "Space Dock G.E.C.K.",
    "starDock-seeder": "Space Dock Bioseeder Ship",
    "starDock-prep_ship": "Space Dock Prep Ship",
    "starDock-launch_ship": "Space Dock Launch Ship",

    "space-belt_mission": "Belt Mission",
    "space-space_station": "Belt Space Station",
    "space-elerium_ship": "Belt Elerium Mining Ship",
    "space-iridium_ship": "Belt Iridium Mining Ship",
    "space-iron_ship": "Belt Iron Mining Ship",

    "space-dwarf_mission": "Dwarf Mission",
    "space-elerium_contain": "Dwarf Elerium Storage",
    "space-e_reactor": "Dwarf Elerium Reactor",
    "space-world_collider": "Dwarf World Collider",
    "space-world_controller": "Dwarf World Collider (Complete)",
    "space-shipyard": "Dwarf Ship Yard",
    "space-mass_relay": "Dwarf Mass Relay",
    "space-m_relay": "Dwarf Mass Relay (Complete)",

    "space-titan_mission": "Titan Mission",
    "space-titan_spaceport": "Titan Spaceport",
    "space-electrolysis": "Titan Electrolysis",
    "space-hydrogen_plant": "Titan Hydrogen Plant",
    "space-titan_quarters": "Titan Habitat",
    "space-titan_mine": "Titan Mine",
    "space-storehouse": "Titan Storehouse",
    "space-titan_bank": "Titan Bank",
    "space-g_factory": "Titan Graphene Plant",
    "space-sam": "Titan SAM Site",
    "space-decoder": "Titan Decoder",
    "space-ai_core": "Titan AI Core",
    "space-ai_core2": "Titan AI Core (Complete)",
    "space-ai_colonist": "Titan AI Colonist",
    "space-enceladus_mission": "Enceladus Mission",
    "space-water_freighter": "Enceladus Water Freighter",
    "space-zero_g_lab": "Enceladus Zero Gravity Lab",
    "space-operating_base": "Enceladus Operational Base",
    "space-munitions_depot": "Enceladus Munitions Depot",
    "space-triton_mission": "Triton Mission",
    "space-fob": "Triton Forward Base",
    "space-lander": "Triton Troop Lander",
    "space-crashed_ship": "Triton Derelict Ship",
    "space-kuiper_mission": "Kuiper Mission",
    "space-orichalcum_mine": "Kuiper Orichalcum Mine",
    "space-uranium_mine": "Kuiper Uranium Mine",
    "space-neutronium_mine": "Kuiper Neutronium Mine",
    "space-elerium_mine": "Kuiper Elerium Mine",
    "space-eris_mission": "Eris Mission",
    "space-drone_control": "Eris Control Relay",
    "space-shock_trooper": "Eris Android Trooper",
    "space-tank": "Eris Tank",
    "space-digsite": "Eris Digsite",
    "tauceti-ringworld": "Tau Star Ringworld",
    "tauceti-matrix": "Tau Star Matrix",
    "tauceti-blue_pill": "Tau Star Blue Pill",
    "tauceti-goe_facility": "Tau Star Garden of Eden",

    "tauceti-home_mission": "Tau Mission",
    "tauceti-dismantle": "Tau Dismantle Ship",
    "tauceti-orbital_station": "Tau Orbital Station",
    "tauceti-colony": "Tau Colony",
    "tauceti-tau_housing": "Tau Housing",
    "tauceti-captive_housing": "Tau Captive Housing",
    "tauceti-pylon": "Tau Pylon",
    "tauceti-cloning_facility": "Tau Cloning",
    "tauceti-horseshoe": "Tau Horseshoe",
    "tauceti-assembly": "Tau Assembly",
    "tauceti-nanite_factory": "Tau Nanite Factory",
    "tauceti-tau_farm": "Tau High-Tech Farm",
    "tauceti-mining_pit": "Tau Mining Pit",
    "tauceti-excavate": "Tau Excavate",
    "tauceti-alien_outpost": "Tau Alien Outpost",
    "tauceti-jump_gate": "Tau Jump Gate",
    "tauceti-fusion_generator": "Tau Fusion Generator",
    "tauceti-repository": "Tau Repository",
    "tauceti-tau_factory": "Tau High-Tech Factory",
    "tauceti-infectious_disease_lab": "Tau Disease Lab",
    "tauceti-tauceti_casino": "Tau Casino",
    "tauceti-tau_cultural_center": "Tau Cultural Center",

    "tauceti-red_mission": "Tau Red Mission",
    "tauceti-orbital_platform": "Tau Red Orbital Platform",
    "tauceti-contact": "Tau Red Contact",
    "tauceti-introduce": "Tau Red Introduce",
    "tauceti-subjugate": "Tau Red Subjugate",
    "tauceti-jeff": "Tau Red Jeff",
    "tauceti-overseer": "Tau Red Overseer",
    "tauceti-womling_village": "Tau Red Womling Village",
    "tauceti-womling_farm": "Tau Red Womling Farm",
    "tauceti-womling_mine": "Tau Red Womling Mine",
    "tauceti-womling_fun": "Tau Red Womling Theater",
    "tauceti-womling_lab": "Tau Red Womling Lab",

    "tauceti-gas_contest": "Tau Gas Naming Contest",
    "tauceti-gas_contest-a1": "Tau Gas Name 1",
    "tauceti-gas_contest-a2": "Tau Gas Name 2",
    "tauceti-gas_contest-a3": "Tau Gas Name 3",
    "tauceti-gas_contest-a4": "Tau Gas Name 4",
    "tauceti-gas_contest-a5": "Tau Gas Name 5",
    "tauceti-gas_contest-a6": "Tau Gas Name 6",
    "tauceti-gas_contest-a7": "Tau Gas Name 7",
    "tauceti-gas_contest-a8": "Tau Gas Name 8",
    "tauceti-refueling_station": "Tau Gas Refueling Station",
    "tauceti-ore_refinery": "Tau Gas Ore Refinery",
    "tauceti-whaling_station": "Tau Gas Whale Processor",
    "tauceti-womling_station": "Tau Gas Womling Station",

    "tauceti-roid_mission": "Tau Belt Mission",
    "tauceti-patrol_ship": "Tau Belt Patrol Ship",
    "tauceti-mining_ship": "Tau Belt Extractor Ship",
    "tauceti-whaling_ship": "Tau Belt Whaling Ship",

    "tauceti-gas_contest2": "Tau Gas 2 Naming Contest",
    "tauceti-gas_contest-b1": "Tau Gas 2 Name 1",
    "tauceti-gas_contest-b2": "Tau Gas 2 Name 2",
    "tauceti-gas_contest-b3": "Tau Gas 2 Name 3",
    "tauceti-gas_contest-b4": "Tau Gas 2 Name 4",
    "tauceti-gas_contest-b5": "Tau Gas 2 Name 5",
    "tauceti-gas_contest-b6": "Tau Gas 2 Name 6",
    "tauceti-gas_contest-b7": "Tau Gas 2 Name 7",
    "tauceti-gas_contest-b8": "Tau Gas 2 Name 8",
    "tauceti-alien_station_survey": "Tau Gas 2 Alien Station (Survey)",
    "tauceti-alien_station": "Tau Gas 2 Alien Station",
    "tauceti-alien_space_station": "Tau Gas 2 Alien Space Station",
    "tauceti-matrioshka_brain": "Tau Gas 2 Matrioshka Brain",
    "tauceti-ignition_device": "Tau Gas 2 Ignition Device",
    "tauceti-ignite_gas_giant": "Tau Gas 2 Ignite Gas Giant",

    "interstellar-alpha_mission": "Alpha Centauri Mission",
    "interstellar-starport": "Alpha Starport",
    "interstellar-habitat": "Alpha Habitat",
    "interstellar-mining_droid": "Alpha Mining Droid",
    "interstellar-processing": "Alpha Processing Facility",
    "interstellar-fusion": "Alpha Fusion Reactor",
    "interstellar-laboratory": "Alpha Laboratory",
    "interstellar-exchange": "Alpha Exchange",
    "interstellar-g_factory": "Alpha Graphene Plant",
    "interstellar-warehouse": "Alpha Warehouse",
    "interstellar-int_factory": "Alpha Mega Factory",
    "interstellar-luxury_condo": "Alpha Luxury Condo",
    "interstellar-zoo": "Alpha Exotic Zoo",

    "interstellar-proxima_mission": "Proxima Mission",
    "interstellar-xfer_station": "Proxima Transfer Station",
    "interstellar-cargo_yard": "Proxima Cargo Yard",
    "interstellar-cruiser": "Proxima Patrol Cruiser",
    "interstellar-dyson": "Proxima Dyson Sphere (Adamantite)",
    "interstellar-dyson_sphere": "Proxima Dyson Sphere (Bolognium)",
    "interstellar-orichalcum_sphere": "Proxima Dyson Sphere (Orichalcum)",

    "interstellar-nebula_mission": "Nebula Mission",
    "interstellar-nexus": "Nebula Nexus",
    "interstellar-harvester": "Nebula Harvester",
    "interstellar-elerium_prospector": "Nebula Elerium Prospector",

    "interstellar-neutron_mission": "Neutron Mission",
    "interstellar-neutron_miner": "Neutron Miner",
    "interstellar-citadel": "Neutron Citadel Station",
    "interstellar-stellar_forge": "Neutron Stellar Forge",

    "interstellar-blackhole_mission": "Blackhole Mission",
    "interstellar-far_reach": "Blackhole Farpoint",
    "interstellar-stellar_engine": "Blackhole Stellar Engine",
    "interstellar-mass_ejector": "Blackhole Mass Ejector",

    "interstellar-jump_ship": "Blackhole Jump Ship",
    "interstellar-wormhole_mission": "Blackhole Wormhole Mission",
    "interstellar-stargate": "Blackhole Stargate",
    "interstellar-s_gate": "Blackhole Stargate (Complete)",

    "interstellar-sirius_mission": "Sirius Mission",
    "interstellar-sirius_b": "Sirius B Analysis",
    "interstellar-space_elevator": "Sirius Space Elevator",
    "interstellar-gravity_dome": "Sirius Gravity Dome",
    "interstellar-ascension_machine": "Sirius Ascension Machine",
    "interstellar-ascension_trigger": "Sirius Ascension Machine (Complete)",
    "interstellar-ascend": "Sirius Ascend",
    "interstellar-thermal_collector": "Sirius Thermal Collector",

    "galaxy-gateway_mission": "Gateway Mission",
    "galaxy-starbase": "Gateway Starbase",
    "galaxy-ship_dock": "Gateway Ship Dock",

    "galaxy-bolognium_ship": "Gateway Bolognium Ship",
    "galaxy-scout_ship": "Gateway Scout Ship",
    "galaxy-corvette_ship": "Gateway Corvette Ship",
    "galaxy-frigate_ship": "Gateway Frigate Ship",
    "galaxy-cruiser_ship": "Gateway Cruiser Ship",
    "galaxy-dreadnought": "Gateway Dreadnought",

    "galaxy-gateway_station": "Stargate Station",
    "galaxy-telemetry_beacon": "Stargate Telemetry Beacon",
    "galaxy-gateway_depot": "Stargate Depot",
    "galaxy-defense_platform": "Stargate Defense Platform",

    "galaxy-gorddon_mission": "Gorddon Mission",
    "galaxy-embassy": "Gorddon Embassy",
    "galaxy-dormitory": "Gorddon Dormitory",
    "galaxy-symposium": "Gorddon Symposium",
    "galaxy-freighter": "Gorddon Freighter",

    "galaxy-consulate": "Alien 1 Consulate",
    "galaxy-resort": "Alien 1 Resort",
    "galaxy-vitreloy_plant": "Alien 1 Vitreloy Plant",
    "galaxy-super_freighter": "Alien 1 Super Freighter",

    "galaxy-alien2_mission": "Alien 2 Mission",
    "galaxy-foothold": "Alien 2 Foothold",
    "galaxy-armed_miner": "Alien 2 Armed Miner",
    "galaxy-ore_processor": "Alien 2 Ore Processor",
    "galaxy-scavenger": "Alien 2 Scavenger",

    "galaxy-chthonian_mission": "Chthonian Mission",
    "galaxy-minelayer": "Chthonian Mine Layer",
    "galaxy-excavator": "Chthonian Excavator",
    "galaxy-raider": "Chthonian Corsair",

    "portal-turret": "Portal Laser Turret",
    "portal-carport": "Portal Surveyor Carport",
    "portal-war_droid": "Portal War Droid",
    "portal-repair_droid": "Portal Repair Droid",

    "portal-war_drone": "Badlands Predator Drone",
    "portal-sensor_drone": "Badlands Sensor Drone",
    "portal-attractor": "Badlands Attractor Beacon",

    "portal-pit_mission": "Pit Mission",
    "portal-assault_forge": "Pit Assault Forge",
    "portal-soul_forge": "Pit Soul Forge",
    "portal-gun_emplacement": "Pit Gun Emplacement",
    "portal-soul_attractor": "Pit Soul Attractor",
    "portal-soul_capacitor": "Pit Soul Capacitor (Witch Hunting)",
    "portal-absorption_chamber": "Pit Absorption Chamber (Witch Hunting)",

    "portal-ruins_mission": "Ruins Mission",
    "portal-guard_post": "Ruins Guard Post",
    "portal-vault": "Ruins Vault",
    "portal-archaeology": "Ruins Archaeology",
    "portal-arcology": "Ruins Arcology",
    "portal-hell_forge": "Ruins Infernal Forge",
    "portal-inferno_power": "Ruins Inferno Reactor",
    "portal-ancient_pillars": "Ruins Ancient Pillars",

    "portal-gate_mission": "Gate Mission",
    "portal-east_tower": "Gate East Tower",
    "portal-west_tower": "Gate West Tower",
    "portal-gate_turret": "Gate Turret",
    "portal-infernite_mine": "Gate Infernite Mine",

    "portal-lake_mission": "Lake Mission",
    "portal-harbor": "Lake Harbor",
    "portal-cooling_tower": "Lake Cooling Tower",
    "portal-bireme": "Lake Bireme Warship",
    "portal-transport": "Lake Transport",

    "portal-spire_mission": "Spire Mission",
    "portal-purifier": "Spire Purifier",
    "portal-port": "Spire Port",
    "portal-base_camp": "Spire Base Camp",
    "portal-bridge": "Spire Bridge",
    "portal-sphinx": "Spire Sphinx",
    "portal-bribe_sphinx": "Spire Bribe Sphinx",
    "portal-spire_survey": "Spire Survey Tower",
    "portal-mechbay": "Spire Mech Bay",
    "portal-spire": "Spire Tower",
    "portal-waygate": "Spire Waygate",

    "launch_facility": "Launch Facility",
    "lhc": "Supercollider",
    "stock_exchange": "Stock Exchange",
    "monument": "Monument",
    "railway": "Railway",
    "nexus": "Nexus",
    "roid_eject": "Asteroid Redirect",
    "syphon": "Mana Syphon",
    "tp_depot": "Depot",
};
