export default {
    "tech-wooden_tools": ["Wooden Tools", "Bone Tools"],
    "tech-cottage": ["Cottage"],
    "tech-apartment": ["Apartment"],
    "tech-oil_power": ["Oil Powerplant", "Wind Farm"],
    "tech-club": ["Club"],
    "tech-bone_tools": ["Bone Tools"],
    "tech-sundial": ["Sundial", "Moondial"],
    "tech-wheel": ["Wheel"],
    "tech-wagon": ["Wagon"],
    "tech-steam_engine": ["Steam Engine"],
    "tech-combustion_engine": ["Combustion Engine"],
    "tech-hover_cart": ["Hover Cart"],
    "tech-osha": ["OSHA Regulations"],
    "tech-blackmarket": ["Blackmarket"],
    "tech-pipelines": ["Oil Pipelines"],
    "tech-housing": ["Housing"],
    "tech-arcology": ["Arcology"],
    "tech-steel_beams": ["Steel Beams"],
    "tech-mythril_beams": ["Mythril Beams"],
    "tech-neutronium_walls": ["Neutronium Walls"],
    "tech-bolognium_alloy_beams": ["Bolognium Alloy Beams"],
    "tech-aphrodisiac": ["Aphrodisiac"],
    "tech-fertility_clinic": ["Fertility Clinic"],
    "tech-captive_housing": ["Captive Housing"],
    "tech-torture": ["Torment"],
    "tech-thrall_quarters": ["Thrall Quarters"],
    "tech-psychic_energy": ["Psychic Energy"],
    "tech-psychic_attack": ["Psychic Assault"],
    "tech-psychic_finance": ["Psychic Finance"],
    "tech-psychic_channeling": ["Psychic Channeling"],
    "tech-psychic_efficiency": ["Psychic Efficiency"],
    "tech-mind_break": ["Psychic Mind Break"],
    "tech-psychic_stun": ["Psychic Stun"],
    "tech-spear": ["Flint Spear"],
    "tech-bronze_spear": ["Bronze Spear"],
    "tech-iron_spear": ["Iron Spear"],
    "tech-dowsing_rod": ["Dowsing Rod"],
    "tech-metal_detector": ["Metal Detector"],
    "tech-smokehouse": ["Smokehouse"],
    "tech-lodge": ["Hunting Lodge"],
    "tech-alt_lodge": ["Lodge"],
    "tech-soul_well": ["Soul Well"],
    "tech-compost": ["Composting"],
    "tech-hot_compost": ["Hot Composting"],
    "tech-mulching": ["Mulching"],
    "tech-adv_mulching": ["Advanced Mulching"],
    "tech-agriculture": ["Agriculture"],
    "tech-farm_house": ["Farm Houses"],
    "tech-irrigation": ["Irrigation"],
    "tech-silo": ["Grain Silo"],
    "tech-mill": ["Grain Mill"],
    "tech-windmill": ["Windmill"],
    "tech-windturbine": ["Wind Turbine"],
    "tech-wind_plant": ["Windmill", "Watermill"],
    "tech-gmfood": ["GM Food"],
    "tech-foundry": ["Foundry"],
    "tech-artisans": ["Artisans"],
    "tech-apprentices": ["Apprentices"],
    "tech-carpentry": ["Carpentry"],
    "tech-demonic_craftsman": ["Master Craftsman"],
    "tech-master_craftsman": ["Master Craftsman"],
    "tech-brickworks": ["Brickworks"],
    "tech-machinery": ["Machinery"],
    "tech-cnc_machine": ["CNC Machine"],
    "tech-vocational_training": ["Vocational Training"],
    "tech-stellar_forge": ["Stellar Forge"],
    "tech-stellar_smelting": ["Stellar Smelting"],
    "tech-assembly_line": ["Assembly Line"],
    "tech-automation": ["Factory Automation"],
    "tech-laser_cutters": ["Laser Cutters"],
    "tech-high_tech_factories": ["High-Tech Factory"],
    "tech-theatre": ["Theatre"],
    "tech-playwright": ["Playwright"],
    "tech-magic": ["Techno Wizards", "Illusionists"],
    "tech-superstars": ["Super Stars"],
    "tech-radio": ["Radio"],
    "tech-tv": ["Television"],
    "tech-vr_center": ["VR Center"],
    "tech-zoo": ["Exotic Zoo"],
    "tech-casino": ["Casino"],
    "tech-dazzle": ["Extreme Dazzle"],
    "tech-casino_vault": ["Casino Vault"],
    "tech-otb": ["Off Track Betting"],
    "tech-online_gambling": ["Online Gambling"],
    "tech-bolognium_vaults": ["Bolognium Vault"],
    "tech-mining": ["Mining", "Sap Hardening"],
    "tech-bayer_process": ["Bayer Process"],
    "tech-elysis_process": ["ELYSIS Process"],
    "tech-smelting": ["Smelting"],
    "tech-steel": ["Crucible Steel"],
    "tech-blast_furnace": ["Blast Furnace"],
    "tech-bessemer_process": ["Bessemer Process"],
    "tech-oxygen_converter": ["Oxygen Converter"],
    "tech-electric_arc_furnace": ["Electric Arc Furnace"],
    "tech-hellfire_furnace": ["Hellfire Furnace"],
    "tech-infernium_fuel": ["Infernium Fuel"],
    "tech-iridium_smelting_perk": ["Iridium Smelting"],
    "tech-rotary_kiln": ["Rotary Kiln"],
    "tech-metal_working": ["Metal Working"],
    "tech-iron_mining": ["Iron Mining"],
    "tech-coal_mining": ["Coal Mining"],
    "tech-storage": ["Basic Storage"],
    "tech-reinforced_shed": ["Reinforced Sheds"],
    "tech-barns": ["Barns"],
    "tech-warehouse": ["Warehouse"],
    "tech-cameras": ["Security Cameras"],
    "tech-pocket_dimensions": ["Pocket Dimensions"],
    "tech-ai_logistics": ["AI Shipping Logistics"],
    "tech-containerization": ["Containerization"],
    "tech-reinforced_crates": ["Reinforced Crates"],
    "tech-cranes": ["Cranes"],
    "tech-titanium_crates": ["Titanium-Banded Crates"],
    "tech-mythril_crates": ["Mythril-Plated Crates"],
    "tech-infernite_crates": ["Infernite Crates"],
    "tech-graphene_crates": ["Graphene Crates"],
    "tech-bolognium_crates": ["Bolognium Crates"],
    "tech-steel_containers": ["Steel Containers"],
    "tech-gantry_crane": ["Gantry Cranes"],
    "tech-alloy_containers": ["Alloy Containers"],
    "tech-mythril_containers": ["Mythril Containers"],
    "tech-adamantite_containers": ["Adamantite Containers"],
    "tech-aerogel_containers": ["Aerogel Containers"],
    "tech-bolognium_containers": ["Bolognium Containers"],
    "tech-nanoweave_containers": ["Nanoweave Liners"],
    "tech-evil_planning": ["Urban Planning"],
    "tech-urban_planning": ["Urban Planning"],
    "tech-zoning_permits": ["Zoning Permits"],
    "tech-urbanization": ["Urbanization"],
    "tech-assistant": ["Personal Assistant"],
    "tech-government": ["Government"],
    "tech-theocracy": ["Theocracy"],
    "tech-republic": ["Republic"],
    "tech-socialist": ["Socialist"],
    "tech-corpocracy": ["Corpocracy"],
    "tech-technocracy": ["Technocracy"],
    "tech-federation": ["Federation"],
    "tech-magocracy": ["Magocracy"],
    "tech-governor": ["Governor"],
    "tech-spy": ["Spies"],
    "tech-espionage": ["Espionage"],
    "tech-spy_training": ["Spy Training Facility"],
    "tech-spy_gadgets": ["Spy Gadgets"],
    "tech-code_breakers": ["Code Breakers"],
    "tech-currency": ["Currency"],
    "tech-market": ["Marketplace"],
    "tech-tax_rates": ["Tax Rates"],
    "tech-large_trades": ["Large Volume Trading"],
    "tech-corruption": ["Corrupt Politicians"],
    "tech-massive_trades": ["Massive Volume Trading"],
    "tech-trade": ["Trade Routes"],
    "tech-diplomacy": ["Diplomacy"],
    "tech-freight": ["Freight Trains"],
    "tech-wharf": ["Wharves"],
    "tech-banking": ["Banking"],
    "tech-investing": ["Investing"],
    "tech-vault": ["Bank Vault"],
    "tech-bonds": ["Savings Bonds"],
    "tech-steel_vault": ["Steel Vault"],
    "tech-eebonds": ["Series EE Bonds"],
    "tech-swiss_banking": ["Cheese Banking"],
    "tech-safety_deposit": ["Safety Deposit Box"],
    "tech-stock_market": ["Stock Exchange"],
    "tech-hedge_funds": ["Hedge Funds"],
    "tech-four_oh_one": ["401K"],
    "tech-exchange": ["Galactic Exchange"],
    "tech-foreign_investment": ["Foreign Investment"],
    "tech-mythril_vault": ["Mythril Vault"],
    "tech-neutronium_vault": ["Neutronium Vault"],
    "tech-adamantite_vault": ["Adamantite Vault"],
    "tech-graphene_vault": ["Graphene Vault"],
    "tech-home_safe": ["House Safe"],
    "tech-fire_proof_safe": ["Fire Proof Safe"],
    "tech-tamper_proof_safe": ["Tamper Proof Safe"],
    "tech-monument": ["Monuments"],
    "tech-tourism": ["Tourism"],
    "tech-xeno_tourism": ["Xeno Tourism"],
    "tech-science": ["Scientific Method"],
    "tech-library": ["Dewey Decimal System"],
    "tech-thesis": ["Thesis Papers"],
    "tech-research_grant": ["Research Grants"],
    "tech-scientific_journal": ["Scientific Journal", "Magic Tomes"],
    "tech-adjunct_professor": ["Adjunct Professors"],
    "tech-tesla_coil": ["Tesla Coil"],
    "tech-internet": ["Internet"],
    "tech-observatory": ["Space Observatory"],
    "tech-world_collider": ["World Collider"],
    "tech-laboratory": ["Laboratory", "Wizard Sanctum"],
    "tech-virtual_assistant": ["Virtual Assistant"],
    "tech-dimensional_readings": ["Dimensional Readings"],
    "tech-quantum_entanglement": ["Quantum Entanglement"],
    "tech-expedition": ["Scientific Expeditions", "Magic Expeditions"],
    "tech-subspace_sensors": ["Subspace Sensors"],
    "tech-alien_database": ["Alien Database"],
    "tech-orichalcum_capacitor": ["Orichalcum Capacitor"],
    "tech-advanced_biotech": ["Advanced Biotech"],
    "tech-codex_infinium": ["Codex Infinium"],
    "tech-bioscience": ["Bioscience"],
    "tech-genetics": ["Genetics"],
    "tech-crispr": ["CRISPR-Cas9"],
    "tech-shotgun_sequencing": ["Shotgun Sequencing"],
    "tech-de_novo_sequencing": ["De Novo Sequencing"],
    "tech-dna_sequencer": ["DNA Sequencer", "Code Sequencer"],
    "tech-rapid_sequencing": ["Rapid Gene Sequencing", "Agile Development"],
    "tech-mad_science": ["Mad Science", "Sages"],
    "tech-electricity": ["Electricity"],
    "tech-matter_replicator": ["Matter Replicator", "Antimatter Replicator"],
    "tech-industrialization": ["Industrialization"],
    "tech-electronics": ["Electronics"],
    "tech-fission": ["Nuclear Fission"],
    "tech-arpa": ["A.R.P.A."],
    "tech-rocketry": ["Rocketry"],
    "tech-robotics": ["Advanced Robotics"],
    "tech-lasers": ["Lasers"],
    "tech-artifical_intelligence": ["Artificial Intelligence"],
    "tech-quantum_computing": ["Quantum Computing"],
    "tech-virtual_reality": ["Virtual Reality"],
    "tech-plasma": ["Plasma Beams"],
    "tech-shields": ["Energy Shields"],
    "tech-ai_core": ["AI Supercore"],
    "tech-metaphysics": ["Metaphysics"],
    "tech-orichalcum_analysis": ["Orichalcum Analysis"],
    "tech-cybernetics": ["Cybernetics"],
    "tech-blood_pact": ["Blood Pact"],
    "tech-purify": ["Enhanced Air Filters"],
    "tech-waygate": ["Waygate"],
    "tech-demonic_infusion": ["Demonic Infusion"],
    "tech-gate_key": ["Gate Key"],
    "tech-gate_turret": ["Gate Turret"],
    "tech-infernite_mine": ["Infernite Survey"],
    "tech-study_corrupt_gem": ["Study Corrupt Gem"],
    "tech-soul_binding": ["Soul Binding"],
    "tech-soul_capacitor": ["Soul Capacitor"],
    "tech-absorption_chamber": ["Absorption Chamber"],
    "tech-corrupt_gem_analysis": ["Corrupt Gem Analysis"],
    "tech-hell_search": ["Search Hell Coordinates"],
    "tech-codex_infernium": ["Codex Infernium"],
    "tech-lake_analysis": ["Blood Lake Analysis"],
    "tech-lake_threat": ["Lake Threat"],
    "tech-lake_transport": ["Lake Transport"],
    "tech-cooling_tower": ["Cooling Tower"],
    "tech-miasma": ["Miasma"],
    "tech-incorporeal": ["Incorporeal Existence"],
    "tech-tech_ascension": ["Ascension"],
    "tech-terraforming": ["Terraforming"],
    "tech-cement_processing": ["Cement Processing"],
    "tech-adamantite_processing_flier": ["Adamantite Processing"],
    "tech-adamantite_processing": ["Adamantite Processing"],
    "tech-graphene_processing": ["Graphene Processing"],
    "tech-fusion_power": ["Nuclear Fusion"],
    "tech-infernium_power": ["Inferno Power"],
    "tech-thermomechanics": ["Thermomechanics"],
    "tech-quantum_manufacturing": ["Quantum Manufacturing"],
    "tech-worker_drone": ["Mining Drones"],
    "tech-uranium": ["Uranium Extraction"],
    "tech-uranium_storage": ["Uranium Storage"],
    "tech-uranium_ash": ["Uranium Ash"],
    "tech-breeder_reactor": ["Breeder Reactor"],
    "tech-mine_conveyor": ["Mine Conveyor Belts"],
    "tech-oil_well": ["Oil Derrick"],
    "tech-oil_depot": ["Fuel Depot"],
    "tech-titanium_drills": ["Titanium Drills"],
    "tech-alloy_drills": ["Alloy Drills"],
    "tech-fracking": ["Fracking"],
    "tech-mythril_drills": ["Mythril Drills"],
    "tech-mass_driver": ["Mass Driver"],
    "tech-orichalcum_driver": ["Orichalcum Mass Driver"],
    "tech-polymer": ["Polymer"],
    "tech-fluidized_bed_reactor": ["Fluidized Bed Reactor"],
    "tech-synthetic_fur": ["Synthetic Fur", "Faux Leather"],
    "tech-nanoweave": ["Nanoweave"],
    "tech-stanene": ["Stanene"],
    "tech-nano_tubes": ["Nano Tubes"],
    "tech-scarletite": ["Scarletite"],
    "tech-pillars": ["Pillars Research"],
    "tech-reclaimer": ["Reclaimers"],
    "tech-shovel": ["Shovel"],
    "tech-iron_shovel": ["Iron Shovel"],
    "tech-steel_shovel": ["Steel Shovel"],
    "tech-titanium_shovel": ["Titanium Shovel"],
    "tech-alloy_shovel": ["Alloy Shovel"],
    "tech-mythril_shovel": ["Mythril Shovel"],
    "tech-adamantite_shovel": ["Adamantite Shovel"],
    "tech-stone_axe": ["Primitive Axes"],
    "tech-copper_axes": ["Bronze Axe"],
    "tech-iron_saw": ["Sawmills"],
    "tech-steel_saw": ["Steel Saws"],
    "tech-iron_axes": ["Iron Axe"],
    "tech-steel_axes": ["Steel Axe"],
    "tech-titanium_axes": ["Titanium Axe"],
    "tech-chainsaws": ["Chainsaws"],
    "tech-copper_sledgehammer": ["Bronze Sledgehammer"],
    "tech-iron_sledgehammer": ["Iron Sledgehammer"],
    "tech-steel_sledgehammer": ["Steel Sledgehammer"],
    "tech-titanium_sledgehammer": ["Titanium Sledgehammer"],
    "tech-copper_pickaxe": ["Bronze Pickaxe"],
    "tech-iron_pickaxe": ["Iron Pickaxe"],
    "tech-steel_pickaxe": ["Steel Pickaxe"],
    "tech-jackhammer": ["Jackhammer"],
    "tech-jackhammer_mk2": ["Electric Jackhammer"],
    "tech-adamantite_hammer": ["Adamantite Jackhammer"],
    "tech-copper_hoe": ["Bronze Hoes"],
    "tech-iron_hoe": ["Iron Hoes"],
    "tech-steel_hoe": ["Steel Hoes"],
    "tech-titanium_hoe": ["Titanium Hoes"],
    "tech-adamantite_hoe": ["Adamantite Hoes"],
    "tech-cyber_limbs": ["Cybernetic Worker Limbs"],
    "tech-slave_pens": ["Slave Pens"],
    "tech-slave_market": ["Slave Market"],
    "tech-ceremonial_dagger": ["Ceremonial Dagger"],
    "tech-last_rites": ["Last Rites"],
    "tech-ancient_infusion": ["Ancient Infusion"],
    "tech-garrison": ["Garrison"],
    "tech-mercs": ["Mercenaries"],
    "tech-signing_bonus": ["Signing Bonus"],
    "tech-hospital": ["Hospital"],
    "tech-bac_tanks": ["BAC Tank", "Repair Subroutines"],
    "tech-boot_camp": ["Boot Camp"],
    "tech-vr_training": ["VR Training"],
    "tech-bows": ["Bows"],
    "tech-flintlock_rifle": ["Flintlock Rifle", "Magic Arrows"],
    "tech-machine_gun": ["Machine Gun", "Fire Mages"],
    "tech-bunk_beds": ["Bunk Beds"],
    "tech-rail_guns": ["Rail Guns", "Lightning Caster"],
    "tech-laser_rifles": ["Laser Rifles", "Mana Rifles"],
    "tech-plasma_rifles": ["Plasma Rifles", "Focused Mana Rifles"],
    "tech-disruptor_rifles": ["Disruptor Rifles", "Magic Missile"],
    "tech-gauss_rifles": ["Gauss Rifles", "Magic Word: Kill"],
    "tech-cyborg_soldiers": ["Cyborg Soldiers"],
    "tech-space_marines": ["Space Marines"],
    "tech-hammocks": ["Nanoweave Hammocks"],
    "tech-cruiser": ["Patrol Cruiser"],
    "tech-armor": ["Leather Armor"],
    "tech-plate_armor": ["Plate Armor"],
    "tech-kevlar": ["Kevlar"],
    "tech-nanoweave_vest": ["Nanoweave Vest"],
    "tech-laser_turret": ["Laser Turret"],
    "tech-plasma_turret": ["Plasma Turret"],
    "tech-black_powder": ["Black Powder", "Magic Powder"],
    "tech-dynamite": ["Dynamite"],
    "tech-anfo": ["ANFO"],
    "tech-mad": ["Mutual Destruction"],
    "tech-cement": ["Cement"],
    "tech-rebar": ["Rebar"],
    "tech-steel_rebar": ["Steel Rebar"],
    "tech-portland_cement": ["Portland Cement"],
    "tech-screw_conveyor": ["Screw Conveyor"],
    "tech-adamantite_screws": ["Adamantite Screws"],
    "tech-hunter_process": ["Hunter Process"],
    "tech-kroll_process": ["Kroll Process"],
    "tech-cambridge_process": ["Cambridge Process"],
    "tech-pynn_partical": ["Pynn Particles"],
    "tech-matter_compression": ["Matter Compression"],
    "tech-higgs_boson": ["Higgs Boson"],
    "tech-dimensional_compression": ["Dimension Compression"],
    "tech-theology": ["Theology"],
    "tech-fanaticism": ["Fanaticism"],
    "tech-alt_fanaticism": ["Fanaticism"],
    "tech-ancient_theology": ["Ancient Theology"],
    "tech-study": ["Study Ancients"],
    "tech-encoding": ["Genetic Encoding"],
    "tech-deify": ["Deify Ancients"],
    "tech-infusion": ["Genetic Infusion"],
    "tech-indoctrination": ["Indoctrination"],
    "tech-missionary": ["Missionary"],
    "tech-zealotry": ["Zealotry"],
    "tech-anthropology": ["Anthropology"],
    "tech-alt_anthropology": ["Anthropology"],
    "tech-mythology": ["Mythology"],
    "tech-archaeology": ["Archaeology"],
    "tech-merchandising": ["Merchandising"],
    "tech-astrophysics": ["Astrophysics"],
    "tech-rover": ["Rovers"],
    "tech-probes": ["Space Probes"],
    "tech-starcharts": ["Star Charts"],
    "tech-colonization": ["Colonization"],
    "tech-red_tower": ["Red Control Tower"],
    "tech-space_manufacturing": ["Space Manufacturing"],
    "tech-exotic_lab": ["Exotic Materials Lab"],
    "tech-hydroponics": ["Hydroponics Bays"],
    "tech-dyson_sphere": ["Dyson Sphere"],
    "tech-dyson_swarm": ["Dyson Swarm"],
    "tech-swarm_plant": ["Swarm Plant"],
    "tech-space_sourced": ["Space Sourced"],
    "tech-swarm_plant_ai": ["Swarm Plant AI"],
    "tech-swarm_control_ai": ["Swarm Control AI"],
    "tech-quantum_swarm": ["Quantum Swarm"],
    "tech-perovskite_cell": ["Perovskite Cells"],
    "tech-swarm_convection": ["Swarm Convection"],
    "tech-orichalcum_panels": ["Orichalcum Panels"],
    "tech-dyson_net": ["Dyson Net"],
    "tech-dyson_sphere2": ["Dyson Sphere"],
    "tech-orichalcum_sphere": ["Orichalcum Dyson Plating"],
    "tech-gps": ["GPS Constellation"],
    "tech-nav_beacon": ["Navigation Beacon"],
    "tech-subspace_signal": ["Subspace Beacon"],
    "tech-atmospheric_mining": ["Atmospheric Mining"],
    "tech-helium_attractor": ["Helium Attractor"],
    "tech-ram_scoops": ["Ram Scoops"],
    "tech-elerium_prospecting": ["Elerium Prospecting"],
    "tech-zero_g_mining": ["Zero G Mining"],
    "tech-elerium_mining": ["Elerium Mining"],
    "tech-laser_mining": ["Laser Mining"],
    "tech-plasma_mining": ["Plasma Mining"],
    "tech-elerium_tech": ["Elerium Theory"],
    "tech-elerium_reactor": ["Elerium Reactor"],
    "tech-neutronium_housing": ["Neutronium Housing"],
    "tech-unification": ["Unification"],
    "tech-unification2": ["Unification"],
    "tech-unite": ["Unite Country"],
    "tech-genesis": ["Genesis Project"],
    "tech-star_dock": ["Space Dock"],
    "tech-interstellar": ["Interstellar Probes"],
    "tech-genesis_ship": ["Genesis Ship", "Generational Ship"],
    "tech-geck": ["G.E.C.K."],
    "tech-genetic_decay": ["Gene Therapy"],
    "tech-stabilize_decay": ["Stabilize Decay"],
    "tech-tachyon": ["Tachyon Particles"],
    "tech-warp_drive": ["Alcubierre Drive"],
    "tech-habitat": ["Habitat"],
    "tech-graphene": ["Graphene"],
    "tech-aerogel": ["Aerogel"],
    "tech-mega_manufacturing": ["Mega Manufacturing"],
    "tech-luxury_condo": ["Luxury Condo"],
    "tech-stellar_engine": ["Stellar Engine"],
    "tech-mass_ejector": ["Mass Ejector"],
    "tech-asteroid_redirect": ["Asteroid Redirect"],
    "tech-exotic_infusion": ["Exotic Infusion"],
    "tech-infusion_check": ["Exotic Infusion"],
    "tech-infusion_confirm": ["Exotic Infusion"],
    "tech-stabilize_blackhole": ["Stabilize Black Hole"],
    "tech-veil": ["The Veil"],
    "tech-mana_syphon": ["Mana Syphon"],
    "tech-gravitational_waves": ["Gravitational Waves"],
    "tech-gravity_convection": ["Gravitational Convection"],
    "tech-wormholes": ["Wormholes"],
    "tech-portal": ["Portals"],
    "tech-fortifications": ["Fortifications"],
    "tech-war_drones": ["War Drones"],
    "tech-demon_attractor": ["Demonic Attractor"],
    "tech-combat_droids": ["Combat Droids"],
    "tech-repair_droids": ["Repair Droids"],
    "tech-advanced_predators": ["Advanced Drones"],
    "tech-enhanced_droids": ["Enhanced War Droids"],
    "tech-sensor_drone": ["Sensor Drones"],
    "tech-map_terrain": ["Map Terrain"],
    "tech-calibrated_sensors": ["Calibrated Sensors"],
    "tech-shield_generator": ["Shield Generator"],
    "tech-enhanced_sensors": ["Enhanced Sensors"],
    "tech-xeno_linguistics": ["Xeno Linguistics"],
    "tech-xeno_culture": ["Xeno Culture"],
    "tech-cultural_exchange": ["Cultural Exchange"],
    "tech-shore_leave": ["Shore Leave"],
    "tech-xeno_gift": ["Alien Gift"],
    "tech-industrial_partnership": ["Industrial Partnership"],
    "tech-embassy_housing": ["Embassy Housing"],
    "tech-advanced_telemetry": ["Advanced Telemetry"],
    "tech-defense_platform": ["Defense Platform"],
    "tech-scout_ship": ["Scout Ship"],
    "tech-corvette_ship": ["Corvette Ship"],
    "tech-frigate_ship": ["Frigate Ship"],
    "tech-cruiser_ship": ["Cruiser Ship"],
    "tech-dreadnought": ["Dreadnought"],
    "tech-ship_dock": ["Ship Dock"],
    "tech-ore_processor": ["Ore Processor"],
    "tech-scavenger": ["Tech Scavenger"],
    "tech-coordinates": ["Decrypt Coordinates"],
    "tech-chthonian_survey": ["Chthonian Survey"],
    "tech-gateway_depot": ["Depot"],
    "tech-soul_forge": ["Soul Forge"],
    "tech-soul_attractor": ["Soul Attractor"],
    "tech-soul_absorption": ["Soul Absorption"],
    "tech-soul_link": ["Soul Link"],
    "tech-gun_emplacement": ["Gun Emplacement"],
    "tech-advanced_emplacement": ["Advanced Gun Emplacement"],
    "tech-dial_it_to_11": ["Dial it up to 11"],
    "tech-limit_collider": ["Limit Collider"],
    "tech-mana": ["Mana"],
    "tech-ley_lines": ["Ley Lines"],
    "tech-rituals": ["Rituals"],
    "tech-crafting_ritual": ["Crafting Rituals"],
    "tech-mana_nexus": ["Mana Nexus"],
    "tech-clerics": ["Clerics"],
    "tech-conjuring": ["Conjuring"],
    "tech-res_conjuring": ["Resource Conjuring"],
    "tech-alchemy": ["Alchemy"],
    "tech-transmutation": ["Advanced Transmutation"],
    "tech-secret_society": ["Secret Society"],
    "tech-cultists": ["Cultists"],
    "tech-conceal_ward": ["Concealing Wards"],
    "tech-subtle_rituals": ["Subtle Rituals"],
    "tech-pylon_camouflage": ["Pylon Camouflage"],
    "tech-fake_tech": ["Fake Tech"],
    "tech-concealment": ["Empowered Concealment Wards"],
    "tech-improved_concealment": ["Improved Concealment Wards"],
    "tech-outerplane_summon": ["Outerplane Summon"],
    "tech-dark_bomb": ["Dark Energy Bomb"],
    "tech-bribe_sphinx": ["Bribe Sphinx"],
    "tech-alien_biotech": ["Alien Biotech"],
    "tech-zero_g_lab": ["Zero Gravity Lab"],
    "tech-operating_base": ["Operating Base"],
    "tech-munitions_depot": ["Munitions Depot"],
    "tech-fob": ["Forward Operating Base"],
    "tech-bac_tanks_tp": ["BAC Tank"],
    "tech-medkit": ["Advanced Medkits"],
    "tech-sam_site": ["Planetary Defenses"],
    "tech-data_cracker": ["Data Cracker"],
    "tech-ai_core_tp": ["AI Supercore"],
    "tech-ai_optimizations": ["AI Optimizations"],
    "tech-synthetic_life": ["Synthetic Life"],
    "tech-protocol66": ["Protocol 66"],
    "tech-protocol66a": ["Protocol 66"],
    "tech-terraforming_tp": ["Terraforming"],
    "tech-quantium": ["Quantium"],
    "tech-anitgrav_bunk": ["Anti-Grav Bunks"],
    "tech-higgs_boson_tp": ["Higgs Boson"],
    "tech-long_range_probes": ["Long Range Probes"],
    "tech-strange_signal": ["Strange Signal"],
    "tech-data_analysis": ["Encrypted Data Analysis"],
    "tech-mass_relay": ["Mass Relay"],
    "tech-nav_data": ["Navigation Data"],
    "tech-sensor_logs": ["Tau Ceti Data"],
    "tech-dronewar": ["Drone Warfare"],
    "tech-drone_tank": ["AI Drone Tanks"],
    "tech-stanene_tp": ["Stanene"],
    "tech-graphene_tp": ["Graphene"],
    "tech-virtual_reality_tp": ["Virtual Reality"],
    "tech-electrolysis": ["Electrolysis"],
    "tech-storehouse": ["Titan Storage Facility"],
    "tech-adamantite_vault_tp": ["Adamantite Vault"],
    "tech-titan_bank": ["Titan Banking"],
    "tech-hydrogen_plant": ["Hydrogen Power"],
    "tech-water_mining": ["Water Mining"],
    "tech-mercury_smelting": ["Solar Smelting"],
    "tech-iridium_smelting": ["Iridium Smelting"],
    "tech-adamantite_crates": ["Adamantite Crates"],
    "tech-bolognium_crates_tp": ["Bolognium Crates"],
    "tech-adamantite_containers_tp": ["Adamantite Containers"],
    "tech-quantium_containers": ["Quantium Containers"],
    "tech-unobtainium_containers": ["Unobtainium Containers"],
    "tech-reinforced_shelving": ["Reinforced Shelving"],
    "tech-garage_shelving": ["Quantium Garage Shelving"],
    "tech-warehouse_shelving": ["Automated Warehousing System"],
    "tech-elerium_extraction": ["Elerium Extraction"],
    "tech-orichalcum_panels_tp": ["Orichalcum Panels"],
    "tech-shipyard": ["Dwarf Ship Yard"],
    "tech-ship_lasers": ["Ship Lasers"],
    "tech-pulse_lasers": ["Ship Pulse Lasers"],
    "tech-ship_plasma": ["Ship Plasma Beams"],
    "tech-ship_phaser": ["Ship Phasers"],
    "tech-ship_disruptor": ["Ship Disruptor"],
    "tech-destroyer_ship": ["Destroyer"],
    "tech-cruiser_ship_tp": ["Cruiser"],
    "tech-h_cruiser_ship": ["Battlecruiser"],
    "tech-dreadnought_ship": ["Dreadnought"],
    "tech-pulse_engine": ["Pulse Drive"],
    "tech-photon_engine": ["Photon Drive"],
    "tech-vacuum_drive": ["Vacuum Drive"],
    "tech-ship_fusion": ["Fusion Generator"],
    "tech-ship_elerium": ["Elerium Generator"],
    "tech-quantum_signatures": ["Quantum Signatures"],
    "tech-interstellar_drive": ["Interstellar Drive"],
    "tech-alien_outpost": ["Alien Outpost"],
    "tech-jumpgates": ["Jump Gates"],
    "tech-system_survey": ["Tau Survey"],
    "tech-repository": ["Repository"],
    "tech-fusion_generator": ["Nuclear Fusion"],
    "tech-tau_cultivation": ["Tau Ceti Cultivation"],
    "tech-tau_manufacturing": ["Tau Ceti Manufacturing"],
    "tech-weasels": ["Weasels"],
    "tech-jeff": ["Contact Jeff"],
    "tech-womling_fun": ["Womling Entertainment"],
    "tech-womling_lab": ["Womling Science"],
    "tech-womling_mining": ["Womling Dirt Excavation"],
    "tech-womling_firstaid": ["Womling First Aid"],
    "tech-womling_logistics": ["Womling Logistics"],
    "tech-womling_repulser": ["Womling Repulser Pad"],
    "tech-womling_farming": ["Womling Farming"],
    "tech-womling_housing": ["Womling Housing"],
    "tech-womling_support": ["Womling Support"],
    "tech-womling_recycling": ["Womling Recycling"],
    "tech-asteroid_analysis": ["Asteroid Data Analysis"],
    "tech-shark_repellent": ["Shark Repellent"],
    "tech-belt_mining": ["Tau Ceti Belt Mining"],
    "tech-adv_belt_mining": ["Advanced Belt Mining"],
    "tech-space_whaling": ["Space Whaling"],
    "tech-infectious_disease_lab": ["Infectious Disease Lab", "Malicious Code Lab"],
    "tech-isolation_protocol": ["Isolation Protocol"],
    "tech-focus_cure": ["Focus Cure"],
    "tech-decode_virus": ["Decode Virus"],
    "tech-vaccine_campaign": ["Vaccination Campaign"],
    "tech-vax_strat1": ["Propaganda Campaign"],
    "tech-vax_strat2": ["Force Vaccination"],
    "tech-vax_strat3": ["Show the Science"],
    "tech-vax_strat4": ["Secret Vaccination"],
    "tech-cloning": ["Cloning Facility"],
    "tech-clone_degradation": ["Clone Degradation"],
    "tech-digital_paradise": ["Digital Paradise"],
    "tech-ringworld": ["Design a Ringworld"],
    "tech-iso_gambling": ["Pit Bosses"],
    "tech-outpost_boost": ["Alien Outpost Device"],
    "tech-cultural_center": ["Cultural Center"],
    "tech-outer_tau_survey": ["Survey Outer Planet"],
    "tech-alien_research": ["Alien Research"],
    "tech-womling_gene_therapy": ["Womling Gene Therapy"],
    "tech-food_culture": ["Sell fruitcake"],
    "tech-advanced_refinery": ["Advanced Ore Refinery"],
    "tech-advanced_pit_mining": ["Advanced Pit Mining"],
    "tech-useless_junk": ["Useless Junk"],
    "tech-advanced_asteroid_mining": ["Advanced Asteroid Mining"],
    "tech-advanced_material_synthesis": ["Advanced Material Synthesis"],
    "tech-matrioshka_brain": ["Matrioshka Brain"],
    "tech-ignition_device": ["Ignition Device"],
    "tech-replicator": ["Matter Replicator", "Antimatter Replicator"],
    "tech-womling_unlock": ["Meet The Neighbors"],
    "tech-garden_of_eden": ["Garden of Eden"],
};
