export const minorTraits = {
    tactical: "Tactical",
    analytical: "Analytical",
    promiscuous: "Promiscuous",
    resilient: "Resilient",
    cunning: "Cunning",
    hardy: "Hardy",
    ambidextrous: "Ambidextrous",
    industrious: "Industrious",
    content: "Content",
    fibroblast: "Fibroblast",
    metallurgist: "Metallurgist",
    gambler: "Gambler",
    persuasive: "Persuasive",
    fortify: "Fortify",
    mastery: "Mastery"
};

export const majorTraits = {
    adaptable: "Adaptable",
    wasteful: "Wasteful",
    xenophobic: "Xenophobic",
    carnivore: "Carnivore",
    beast: "Beast",
    cautious: "Cautious",
    herbivore: "Herbivore",
    instinct: "Instincts",
    small: "Small",
    weak: "Weak",
    large: "Large",
    strong: "Strong",
    cold_blooded: "Cold Blooded",
    scales: "Scales",
    flier: "Flier",
    hollow_bones: "Hollow Bones",
    sky_lover: "Sky Lover",
    rigid: "Rigid",
    high_pop: "High Population",
    fast_growth: "Fast Growth",
    high_metabolism: "High Metabolism",
    photosynth: "Photosynth",
    sappy: "Sappy",
    asymmetrical: "Asymmetrical",
    detritivore: "Detritivore",
    spores: "Spores",
    spongy: "Spongy",
    submerged: "Submerged",
    low_light: "Low Light",
    elusive: "Elusive",
    iron_allergy: "Iron Allergy",
    smoldering: "Smoldering",
    cold_intolerance: "Cold Intolerance",
    chilled: "Chilled",
    heat_intolerance: "Heat Intolerance",
    scavenger: "Scavenger",
    nomadic: "Nomadic",
    immoral: "Immoral",
    evil: "Evil",
    blissful: "Blissful",
    pompous: "Pompous",
    holy: "Holy",
    artifical: "Artificial",
    powered: "Powered",
    psychic: "Psychic",
    tormented: "Tormented",
    darkness: "Darkness",
    unfathomable: "Unfathomable",
    creative: "Creative",
    diverse: "Diverse",
    studious: "Studious",
    arrogant: "Arrogant",
    brute: "Brute",
    angry: "Angry",
    lazy: "Lazy",
    curious: "Curious",
    pack_mentality: "Pack Mentality",
    tracker: "Tracker",
    playful: "Playful",
    freespirit: "Free Spirit",
    beast_of_burden: "Beast of Burden",
    sniper: "Sniper",
    hooved: "Hooved",
    rage: "Rage",
    heavy: "Heavy",
    gnawer: "Gnawer",
    calm: "Calm",
    pack_rat: "Pack Rat",
    paranoid: "Paranoid",
    greedy: "Greedy",
    merchant: "Merchant",
    smart: "Smart",
    puny: "Puny",
    dumb: "Dumb",
    tough: "Tough",
    nearsighted: "Nearsighted",
    intelligent: "Intelligent",
    regenerative: "Regenerative",
    gluttony: "Gluttony",
    slow: "Slow",
    armored: "Armored",
    optimistic: "Optimistic",
    chameleon: "Chameleon",
    slow_digestion: "Slow Digestion",
    hard_of_hearing: "Hard of Hearing",
    resourceful: "Resourceful",
    selenophobia: "Selenophobia",
    leathery: "Leathery",
    pessimistic: "Pessimistic",
    hoarder: "Hoarder",
    solitary: "Solitary",
    kindling_kindred: "Kindling Kindred",
    pyrophobia: "Pyrophobia",
    hyper: "Hyper",
    skittish: "Skittish",
    fragrant: "Fragrant",
    sticky: "Sticky",
    infectious: "Infectious",
    parasite: "Parasite",
    toxic: "Toxic",
    nyctophilia: "Nyctophilia",
    infiltrator: "Infiltrator",
    hibernator: "Hibernator",
    cannibalize: "Cannibalize",
    frail: "Frail",
    malnutrition: "Malnutrition",
    claws: "Claws",
    atrophy: "Atrophy",
    hivemind: "Hivemind",
    tunneler: "Tunneler",
    blood_thirst: "Blood Thirst",
    apex_predator: "Apex Predator",
    invertebrate: "Invertebrate",
    suction_grip: "Suction Grip",
    befuddle: "Befuddle",
    environmentalist: "Environmentalist",
    unorganized: "Unorganized",
    musical: "Musical",
    revive: "Revive",
    slow_regen: "Slow Regen",
    forge: "Forge",
    autoignition: "Autoignition",
    blurry: "Blurry",
    snowy: "Snowy",
    ravenous: "Ravenous",
    ghostly: "Ghostly",
    lawless: "Lawless",
    mistrustful: "Mistrustful",
    humpback: "Humpback",
    thalassophobia: "Thalassophobia",
    fiery: "Fiery",
    terrifying: "Terrifying",
    slaver: "Slaver",
    compact: "Compact",
    conniving: "Conniving",
    pathetic: "Pathetic",
    spiritual: "Spiritual",
    truthful: "Truthful",
    unified: "Unified",
    rainbow: "Rainbow",
    magnificent: "Magnificent",
    noble: "Noble",
    imitation: "Imitation",
    emotionless: "Emotionless",
    logical: "Logical",
    shapeshifter: "Mimic",
    deconstructor: "Deconstructor",
    linked: "Linked",
    dark_dweller: "Dark Dweller",
    swift: "Swift",
    anthropophagite: "Anthropophagite",
    living_tool: "Living Tool",
    bloated: "Bloated",
    ooze: "Ooze",
    soul_eater: "Soul Eater",
    untapped: "Untapped Potential",
    emfield: "Electromagnetic Field",
};

export const traits = {
    ...majorTraits,
    ...minorTraits
};
